default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5

development:
  <<: *default
  database: portal_solar_development

test:
  <<: *default
  database: portal_solar_test
